name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.HOST }}
       USERNAME: ${{ secrets.USERNAME }}
       PORT: ${{ secrets.PORT }}
       KEY: ${{ secrets.SSHKEY }}
       script: |
          cd ~/home/flaminio/repository_githubAction
          mkdir pippo
   
