name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy repository contents via scp
      uses: garygrossgarten/github-action-scp@release
      with:
          local: .
          remote: .
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          privateKey : ${{ secrets.SSHKEY }}
        
   
